# Generated by Django 6.0 on 2025-12-27 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=0, message="Price must be greater or equal to 0"
                    )
                ],
            ),
        ),
    ]
