# Generated by Django 5.2 on 2026-01-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_content", "0002_alter_service_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="servicetype",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
