# Generated by Django 5.2 on 2026-02-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_content", "0003_alter_service_id_alter_servicetype_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="description_uk",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="name_uk",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="servicetype",
            name="name_en",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="servicetype",
            name="name_uk",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
