# Generated by Django 6.0 on 2025-12-22 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="order",
            name="total_price",
        ),
        migrations.AlterField(
            model_name="address",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="crm.customer",
            ),
        ),
        migrations.AlterField(
            model_name="careerform",
            name="phone",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="contactform",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_forms",
                to="crm.customer",
            ),
        ),
        migrations.AlterField(
            model_name="contactform",
            name="phone",
            field=models.CharField(max_length=20),
        ),
    ]
