# Generated by Django 6.0 on 2025-12-22 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_remove_order_quantity_remove_order_total_price_and_more"),
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="addresses",
                to="operations.region",
            ),
        ),
    ]
