# Generated by Django 6.0 on 2025-12-23 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_alter_address_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="crm.address",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="scheduled",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
