# Generated by Django 6.0 on 2025-12-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_order_address_order_scheduled"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactform",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
