# Generated by Django 6.0 on 2025-12-30 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_contactform_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careerform",
            name="description",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        limit_value=500, message="Description too long"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="contactform",
            name="description",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        limit_value=500, message="Description too long"
                    )
                ],
            ),
        ),
    ]
