# Generated by Django 6.0 on 2026-01-06 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_alter_careerform_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="scheduled",
            new_name="scheduled_at",
        ),
    ]
